dist: xenial

language: python

branches:
  only:
    - master

matrix:
  include:
    - stage: Tests (Python 3.8)
      python: 3.8
      env: TOXENV=py38

    - stage: Tests (Python 3.7)
      python: 3.7
      env: TOXENV=py37

    - stage: Tests 3.6 (Python 3.6)
      python: 3.6
      env: TOXENV=py36

    - stage: Docs (Python 3.8)
      python: 3.8
      env: TOXENV=docs

install:
  - pip install tox
  - pip install apache-airflow
  - airflow initdb

script:
  - tox